### ISSUE TITLE
Question: Working with Flux/Redux

### ISSUE THREAD

**Issue by kjanoudi** [appersonlabs/react-joi-forms#7]
Hello,

I'm trying to get this working with redux to fill in data from the database. When i get back my data, i call setState to set the values. Typically, in a normal form, this will call render() and the value of my field is filled into the textbox. If i use this module, and i call setState, there is still nothing in the value of the textbox. I tried passing it in via `values` but that seems to only matter in `getInitialState` which is only called on the first render. What am i missing here? Is there a way to get it working with values that im pulling from a database using redux/flux flow?

Thanks

**Comment by kjanoudi** [comment]
Would it make sense to move this:

``` javascript
getInitialState: function getInitialState() {
      ...

        if (this.props.schema) {
            this.props.schema.forEach(function (fieldSchema) {

                var name = fieldSchema._meta.name || _this2._camelize(fieldSchema._settings.language.label);

                // if no value set for this field, but their is a default, set it
                if (state.values[name] === undefined && fieldSchema._flags['default'] !== undefined) {
                    state.values[name] = fieldSchema._flags['default'];
                }
                if (state.values[name] === undefined && fieldSchema._type === 'boolean') {
                    state.values[name] = false;
                }
            });
        }
        return state;
    },

```

into 

``` javascript

componentWillReceiveProps: function componentWillReceiveProps(nextProps) {
      ...
        if (nextProps.schema) {
            nextProps.schema.forEach(function (fieldSchema) {
                schema[_this3._camelize(fieldSchema._settings.language.label)] = fieldSchema;
            });
        }

        this.setState(_extends({}, this.state, {
            schema: schema,
            values: values
        }));
    },

```

**Comment by Georgette** [comment]
Hi @kjanoudi , I'll try to reproduce and get back to you over the weekend. You are also more than welcome to see if you can troubleshoot and contribute a possible fix too :)

**Comment by mattapperson** [comment]
@kjanoudi @Georgette  yes and no. `componentWillReceiveProps` is only called on subsequent redraws, not with the initial mount. The code needs to be abstracted out into its own method and called via both `componentWillReceiveProps` AND `getInitialState`
